name: almuhasib_mobile
description: قيد — تطبيق جوال للتقارير ولوحة التحكم
publish_to: 'none'
version: 1.11.0+11

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.7.2
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  easy_localization: ^3.0.7+1
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.4
  intl: ^0.20.2
  onesignal_flutter: ^5.3.0
  device_info_plus: ^11.3.3
  uuid: ^4.5.1
  flutter_animate: ^4.5.2
  package_info_plus: ^8.3.0
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/qayd-icon.png
  adaptive_icon_background: "#051020"
  adaptive_icon_foreground: assets/images/qayd-icon.png
  remove_alpha_ios: true
  background_color_ios: "#051020"

flutter_native_splash:
  color: "#051020"
  color_dark: "#051020"
  image: assets/images/qayd-icon.png
  image_dark: assets/images/qayd-icon.png
  android_12:
    color: "#051020"
    color_dark: "#051020"
    image: assets/images/qayd-icon.png
    image_dark: assets/images/qayd-icon.png
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - .env
