<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AlMuhasib.Core\AlMuhasib.Core.csproj" />
    <ProjectReference Include="..\..\src\AlMuhasib.Infrastructure\AlMuhasib.Infrastructure.csproj" />
  </ItemGroup>
</Project>
